import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home({ products }) {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Productos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Productos</h1>
      <div className={styles.products__box}>
        {products.data.map((product, index) => (
          <div className={styles.product__item} key={index}>
            <img
              src={`${process.env.NEXT_PUBLIC_API_URL}${product.attributes?.image?.data.attributes.formats.thumbnail.url}`}
              width="200"
              height="200"
            />
            <h2>{product.attributes?.name}</h2>
            <span>${product.attributes?.price}</span>
            <button
              onClick={() =>
                router.push(`/products/${product.attributes?.slug}`)
              }
            >
              Ver producto
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

export async function getServerSideProps({ props }) {
  const data = await fetch(
    `${process.env.API_URL}/products?populate=image,categories`
  );
  const productsData = await data.json();
  return {
    props: {
      products: productsData,
    },
  };
}
